export { DeckClient } from './deck/deckClient'
export { BookmarkClient } from './bookmark/bookmarkClient'
export { AuthClient } from './auth/authClient'
export { NotesClient } from './notes/notesClient'
export { GeneralClient } from './general/generalClient'