export { DeckClient } from './clients/DeckClient'
export { BookmarkClient } from './clients/BookmarkClient'
export { AuthClient } from './clients/AuthClient'
export { NotesClient } from './clients/NotesClient'
export { GeneralClient } from './clients/GeneralClient'
export { oAuthClient } from './clients/oAuthClient'