name: Testing
on: [push, pull_request]
jobs:
  bun-test:
    name: Bun Testing
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun test --coverage
